### ISSUE TITLE
What is prefered now, the svg or the png ext_icon ?

### ISSUE THREAD

**Issue by dhuf** [IchHabRecht/my_skeleton#1]
I saw some new extensions getting the SVG so I was wondering what was preferred. Thanks.

**Comment by IchHabRecht** [comment]
Hi @dhuf,

Since TYPO3 8.7 the location for the extension icon changed to the Resources folder. The icon in root is for compatibility only and is not necessary for newer versions.

**Comment by dhuf** [comment]
@IchHabRecht So true, thanks for the clarification.
